/**
 * Component Desing Sample - Mock API
 * Mock API project to be used for e2e tests
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AuthApi", () => {
  let instance: api.AuthApi
  beforeEach(function() {
    instance = new api.AuthApi(config)
  });

  test("loginPost", () => {
    const body: api.Credentials = undefined
    return expect(instance.loginPost(body, {})).resolves.toBe(null)
  })
  test("logoutPost", () => {
    const body: api.TokenRequest = undefined
    return expect(instance.logoutPost(body, {})).resolves.toBe(null)
  })
  test("tokenPost", () => {
    const body: api.TokenRequest = undefined
    return expect(instance.tokenPost(body, {})).resolves.toBe(null)
  })
})

describe("BookingsApi", () => {
  let instance: api.BookingsApi
  beforeEach(function() {
    instance = new api.BookingsApi(config)
  });

  test("bookingsGet", () => {
    return expect(instance.bookingsGet({})).resolves.toBe(null)
  })
  test("bookingsIdGet", () => {
    const id: number = 56
    return expect(instance.bookingsIdGet(id, {})).resolves.toBe(null)
  })
  test("bookingsPost", () => {
    const body: api.Booking = undefined
    return expect(instance.bookingsPost(body, {})).resolves.toBe(null)
  })
})

describe("ProfilesApi", () => {
  let instance: api.ProfilesApi
  beforeEach(function() {
    instance = new api.ProfilesApi(config)
  });

  test("profilesGet", () => {
    return expect(instance.profilesGet({})).resolves.toBe(null)
  })
  test("profilesIdGet", () => {
    const id: number = 56
    return expect(instance.profilesIdGet(id, {})).resolves.toBe(null)
  })
})

